package com.master.healthcoach.domain

import kotlinx.serialization.Serializable

data class TimedMeasurement(
    val epochMillis: Long,
    val value: Double,
    val origin: String,
)

@Serializable
data class WeeklySnapshot(
    val weekStart: String,
    val weekEnd: String,
    val fatMassChangeKg: Double?,
    val leanMassChangeKg: Double?,
    val weightChangeKg: Double?,
    val bodyMeasurementDays: Int,
    val stepsDailyAverage: Long?,
    val activeCaloriesDailyAverage: Double?,
    val exerciseSessions: Int,
    val exerciseMinutes: Long,
    val strengthMinutes: Long,
    val cardioMinutes: Long,
    val previousWeekStepsDailyAverage: Long?,
    val previousWeekActiveCaloriesDailyAverage: Double?,
    val dataLimitations: List<String>,
    val sleepDailyAverageMinutes: Long? = null,
    val sleepMeasurementDays: Int = 0,
    val moderateIntensityMinutes: Long? = null,
    val vigorousIntensityMinutes: Long? = null,
    val heartRateAverageBpm: Long? = null,
    val heartRateMinimumBpm: Long? = null,
    val heartRateMaximumBpm: Long? = null,
    val heartRateMeasurementDays: Int = 0,
    val basalCaloriesDailyAverage: Double? = null,
    val basalCaloriesMeasurementDays: Int = 0,
    val previousWeekSleepDailyAverageMinutes: Long? = null,
    val previousWeekModerateIntensityMinutes: Long? = null,
    val previousWeekVigorousIntensityMinutes: Long? = null,
    val previousWeekHeartRateAverageBpm: Long? = null,
    val previousWeekBasalCaloriesDailyAverage: Double? = null,
    val currentWeightMedianKg: Double? = null,
    val currentFatMassMedianKg: Double? = null,
    val currentLeanMassMedianKg: Double? = null,
    val weightTrendKgPerWeek: Double? = null,
    val weightLossRatePercentPerWeek: Double? = null,
    val fatMassTrendKgPerWeek: Double? = null,
    val leanMassTrendKgPerWeek: Double? = null,
    val trendMeasurementDays: Int = 0,
    val morningRoutineMinutes: Long = 0,
    val morningRoutineDays: Int = 0,
    val previousWeekMorningRoutineDays: Int = 0,
    val morningRoutineTargetDays: Int = 7,
    val morningRoutineAdherencePercent: Int? = null,
    val stepsTargetHitDays: Int? = null,
    val stepsBaselinePercent: Int? = null,
    val moderateEquivalentMinutes: Long? = null,
    val previousWeekModerateEquivalentMinutes: Long? = null,
    val sleepTargetHitDays: Int? = null,
    val sleepScheduleDeviationMinutes: Long? = null,
    val sleepHeartRateAverageBpm: Long? = null,
    val sleepHeartRateBaselineDeltaBpm: Long? = null,
    val measurementTimeConsistencyPercent: Int? = null,
    val fatMassToGoalKg: Double? = null,
    val requiredFatLossKgPerWeek: Double? = null,
    val dietStartDate: String? = null,
    val intakeCaloriesDailyAverage: Double? = null,
    val proteinDailyAverageGrams: Double? = null,
    val totalFatDailyAverageGrams: Double? = null,
    val carbohydrateDailyAverageGrams: Double? = null,
    val nutritionMeasurementDays: Int = 0,
    val previousWeekIntakeCaloriesDailyAverage: Double? = null,
    val previousWeekProteinDailyAverageGrams: Double? = null,
    val previousWeekTotalFatDailyAverageGrams: Double? = null,
    val previousWeekCarbohydrateDailyAverageGrams: Double? = null,
    val estimatedEnergyBalanceDailyAverage: Double? = null,
    val proteinEnergyPercent: Double? = null,
    val fatEnergyPercent: Double? = null,
    val carbohydrateEnergyPercent: Double? = null,
)

@Serializable
data class AdviceResponse(
    val summary: String,
    val positiveChange: String? = null,
    val caution: String? = null,
    val nextActions: List<String> = emptyList(),
    val habitInsights: List<String> = emptyList(),
    val confidence: String = "medium",
    val dataLimitations: List<String> = emptyList(),
    val clarifyingQuestions: List<String> = emptyList(),
)

data class BodyCalculation(
    val weightKg: Double?,
    val bodyFatPercent: Double?,
    val fatMassKg: Double?,
    val leanMassKg: Double?,
    val leanMassSource: String?,
    val measurementEpochMillis: Long?,
    val origin: String?,
)
